name: Pulumi
on:
  - pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: NodeJS
        uses: actions/setup-node@v1
      - run: npm install
      - run: docker-compose up -d
      - run: npm run initLocal
      - run: npm test
        env:
          CI: true
  preview:
    name: Preview
    runs-on: ubuntu-latest
    if: "false" # This spams the PR requests
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: docker://pulumi/actions
        with:
          args: preview
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_CI: pr
          COMMENT_ON_PR: 1
